### ISSUE TITLE
SUSE12 SP3，The system cannot run properly, and an error message is displayed.

### ISSUE THREAD

**Issue by hzykiss** [rek7/mXtract#9]
ERROR OPENING REGEX DB: example_regexes.db

**Comment by EmailToXjk** [comment]
![image](https://user-images.githubusercontent.com/87066129/163370866-c0db613f-57bd-4a1b-8f2b-58291ab8f33e.png)
In my Ubuntu 10.3.0, I can't bulid it properly.

**Comment by EmailToXjk** [comment]
`sudo ./mxtract -wm -wr -e -i -d=/tmp/output/ -r=../example_regexes.db`
